### ISSUE TITLE
Updated branded build plate for 3D45

### ISSUE THREAD

**Issue by elephantmotor** [timmehtimmeh/Cura-Dremel-3D20-Plugin#101]
Hey Mike,

It has been talked about in the past, but here you go. 

[Dremel_3D45_platform.zip](https://github.com/metalman3797/Cura-Dremel-Printer-Plugin/files/11337472/Dremel_3D45_platform.zip)

**Comment by metalman3797** [comment]
Official Dremel build plate has been added.
