### ISSUE TITLE
Plugin version 1.0.0: Plugin preferences no longer pops up preference dialog box

### ISSUE THREAD

**Issue by timmehtimmeh** [timmehtimmeh/Cura-Dremel-3D20-Plugin#107]
Cura ver 5.6.0:

In plugin version 0.8.1 navigating to extensions->dremel printer plugin->preferences
![image](https://github.com/metalman3797/Cura-Dremel-Printer-Plugin/assets/19733103/533e26fe-0fe6-4363-aea8-6703b2af6a65)

Would pop up a dialog box allowing the user to configure a few settings:
![image](https://github.com/metalman3797/Cura-Dremel-Printer-Plugin/assets/19733103/30d765b1-0cb0-45f4-a0bd-0ae2ebd2e290)

However clicking the the 1.0.0 release the dialog box no longer pops up,
![image](https://github.com/metalman3797/Cura-Dremel-Printer-Plugin/assets/19733103/842810cc-0daa-42e3-a516-3241d71eb568)

**Comment by timmehtimmeh** [comment]
The issue seems to be related to the lines:

`color: "#000000"` in the DremelPluginprefs.qml file.  Removing the three lines that specify the black color allows the popup to appear:

![image](https://github.com/metalman3797/Cura-Dremel-Printer-Plugin/assets/19733103/90e10d7d-4f28-487b-9367-72dc4d237ae0)

The lines I removed are:
[here](https://github.com/metalman3797/Cura-Dremel-Printer-Plugin/blob/113f601ca8c7888ab1dfe02ba11f0061661f8458/plugins/DremelPrinterPlugin/DremelPluginprefs.qml#L48)
[here ](https://github.com/metalman3797/Cura-Dremel-Printer-Plugin/blob/113f601ca8c7888ab1dfe02ba11f0061661f8458/plugins/DremelPrinterPlugin/DremelPluginprefs.qml#L63)and
[here](https://github.com/metalman3797/Cura-Dremel-Printer-Plugin/blob/113f601ca8c7888ab1dfe02ba11f0061661f8458/plugins/DremelPrinterPlugin/DremelPluginprefs.qml#L104)

Sidenote - the window should be made a bit bigger by changing the [minimumHeight ](https://github.com/metalman3797/Cura-Dremel-Printer-Plugin/blob/113f601ca8c7888ab1dfe02ba11f0061661f8458/plugins/DremelPrinterPlugin/DremelPluginprefs.qml#L15)to properly contain the new UI elements that were added.  When the window first pops up it's a bit smaller than the items it contains:
![image](https://github.com/metalman3797/Cura-Dremel-Printer-Plugin/assets/19733103/89d93c33-0ef6-4a0a-ab09-3f65f8bbc4d0)

**Comment by metalman3797** [comment]
Approved changes.  New build uploading today.
