### ISSUE TITLE
1.0.0 not available on the marketplace, how to install manually?

### ISSUE THREAD

**Issue by GINNOV** [timmehtimmeh/Cura-Dremel-3D20-Plugin#110]
It has been almost a year since the 1.0 was posted here and the 0.8 is the only version available on the marketplace. What's the process to install it manually?

**Comment by timmehtimmeh** [comment]
@GINNOV  - see my comment [here](https://github.com/metalman3797/Cura-Dremel-Printer-Plugin/issues/108#issuecomment-2166154751)

**Comment by timmehtimmeh** [comment]
Even though this issue is closed I'll post a comment for anyone running across it in the future that @metalman3797 has successfully uploaded version 1.0.1 to the marketplace  🤘 👨 🥳  🚀
