### ISSUE TITLE
Cannot find plugin in Cura Marketplace & no manual install instructions

### ISSUE THREAD

**Issue by semiconducted** [timmehtimmeh/Cura-Dremel-3D20-Plugin#60]
Cannot find plugin in Cura Marketplace.

I tried to install this manually by moving the files into the correct folders, but no .dgrem file type appears in 'save file' dialog and manually changing file type results in Dremel 3D20 crashing when exported file is loaded.

MacOS: 10.15.1 (19B88)
Cura: 4.2.1

Is this an issue local to just me?

<img width="832" alt="Screen 2019-12-03 at 2 36 46 PM" src="https://user-images.githubusercontent.com/1928889/70083466-69c82680-15da-11ea-8fbf-d4c8963d8731.png">
<img width="832" alt="Screen 2019-12-03 at 2 36 55 PM" src="https://user-images.githubusercontent.com/1928889/70083471-6d5bad80-15da-11ea-8045-8291bc7375d6.png">

**Comment by timmehtimmeh** [comment]
@semiconducted - Unfortunately Cura doesn't have a stable API, and each time they make changes older versions of cura lose access to the plugin in the marketplace.  Please download the appropriate version of the .curaplugin from the releases page here:  https://github.com/timmehtimmeh/Cura-Dremel-3D20-Plugin/releases

Then drag and drop the .curaplugin onto your running cura instance

**Comment by semiconducted** [comment]
Thanks for the incredibly quick reply!
It turns out it WAS a local Cura issue just for folks like me running an older version. 
I had reinstalled Cura before, but the key this time was manually deleting all references to it, i.e. everything in the Application Support folder and reinstalling from scratch. 

I'm now on Cura v 4.4.0 and install worked just as you wrote in the README.md.

Thanks!
<img width="832" alt="Screen 2019-12-03 at 3 24 22 PM" src="https://user-images.githubusercontent.com/1928889/70086818-24f3be00-15e1-11ea-9c67-503b41ce19d2.png">

**Comment by timmehtimmeh** [comment]
Glad to hear you resolved the issue & thanks for the update - it will help anyone else having the issue.  Cheers!
