### ISSUE TITLE
Unable to select

### ISSUE THREAD

**Issue by CeeCeePea** [timmehtimmeh/Cura-Dremel-3D20-Plugin#70]
I am not sure if the issue has to do with the plugin but after a while I cannot select the object on the screen. I have to restart the program and reload the file to be able to select the design.

**Comment by timmehtimmeh** [comment]
Hi @CeeCeePea - most likely this is a Cura issue, and not an issue with this plugin specifically.  It appears that others have had similar issues with Cura- see [here](https://community.ultimaker.com/topic/27891-problem-selecting-items-in-cura-40/) and [here](https://community.ultimaker.com/topic/33478-cant-select-any-objects/) including users who report the issue even with no plugins installed.  Some users have reported the issue occurs in Cura version 4.0 up-to-and-including Cura ver 4.8.  It seems that Ultimaker is at least aware of the issue, as they have a [bug filed here](https://github.com/Ultimaker/Cura/issues/8745)  which the Ultimaker developers are commenting on.

If you're running on MacOS then one user reported [here](https://community.ultimaker.com/topic/33478-cant-select-any-objects/?do=findComment&comment=280264) a possible fix:
> I have MacOS 11.0 - Cura 4.8 - and fixed it with - Adding Cura to "Security & Privacy" - "Privacy" - "Full Disk Access" 

But others report that it did not work for them...feel free to give it a try. 

The Dremel plugin code is only be called when Cura is writing a .g3drem file out - other than that all user interaction is handled by Cura.

**Comment by CeeCeePea** [comment]
Thank you for your prompt response and help. 

CeeCee

**Comment by nallath** [comment]
I'm fairly sure that this is a Cura issue since it also happens with other plugins.
