### ISSUE TITLE
Acceleration Enabled by Default?

### ISSUE THREAD

**Issue by eduncan911** [timmehtimmeh/Cura-Dremel-3D20-Plugin#81]
Hey Tim!

Was looking over your settings from the plugin and noticed that the acceleration flag is enabled to true.

https://github.com/timmehtimmeh/Cura-Dremel-Printer-Plugin/blob/7a10e4969420065aa41a7f38ad84c4c63c235916/resources/definitions/Dremel3D20.def.json#L125-L128

Also noticed it's enabled on the 3D45.

I think this is an issue, because with the flag set to `True`, and no actual acceleration settings set, Cura defaults them to a whopping 3000mm/s/s (and travel at 5000mm/s/s).

For comparison, the Merlin hack for the 3D20 sets them to `200mm/s/s`, and travel to `1000mm/s/s`:

https://github.com/moonglow/FlashForge_Marlin/blob/d26a00b08c14a414e6bb9801ad2706b1aeab6d5b/Marlin/Marlin/Configuration.h#L1000-L1010

So, we could either:

* leave them enabled (true) and set these settings (I'm about to test this 200/1000 combo right now).  
* or, we can just remove the True and default to False - which should use the default Firmware settings.

Whichever you think is correct, I can open a PR for.  Just a little direction of what you are thinking.

---

Btw, 3D45 seems to be nice and quiet at 800/1200 accel and 8.0 jerk.  Otherwise, the 3D45 with default jerk settings sounds like it will rattle apart, which I am sure you have heard.  :)

And the 3D20 is pretty loud on it's jerk settings, so I was going to set it to 5.0 from the Marlin firmware to see how it sounds on this next print in the next hour.

**Comment by timmehtimmeh** [comment]
@eduncan911  - good catch.  The 3D20 acceleration value has been enabled since version [0.6.5](https://github.com/timmehtimmeh/Cura-Dremel-Printer-Plugin/commit/6545575b3c7d89ff84de7308c2f79575240bb5d8) about 5 months ago and you're the first person to bring it to my attention - thanks!

> So, we could either:
> - leave them enabled (true) and set these settings (I'm about to test this 200/1000 combo right now).
 > - or, we can just remove the True and default to False - which should use the default Firmware settings.

If your testing shows that 200/1000 works better than the current settings I have a slight preference to leave the setting as "True" and put the numbers in just so that it's a known number controlled by the plugin, but i'm fine with the first option as well.

Regarding the 3D45 - feel free to modify the accel/jerk for that definition as well if you want and put it in the PR.  When I get home tonight I'll give your suggestions/PR a test

Cheers 

Tim

**Comment by eduncan911** [comment]
Ha, yeah I noticed it to with the old 3D20 plugin and just unchecked it.  Mainly cause I was like, "why is this thing so loud when sliced with Cura (with plugin)?"  I actually think I had a layer shift a long time ago when using the Cura plugin for the 3D20 (which a 3000mm/s/s would cause, if the printer can't handle it!).

**Comment by timmehtimmeh** [comment]
Upon a bit closer inspection it appears that I added the acceleration enabled flag in [version 0.6.5](https://github.com/timmehtimmeh/Cura-Dremel-Printer-Plugin/commit/6545575b3c7d89ff84de7308c2f79575240bb5d8) of the 3D20 plugin about 6 months ago, not in the initial commit (I edited my comment above to reflect that).  Regardless - thank you for finding & reporting the issue.  

As I said I'm totally fine with either solution, if your testing shows that 200/1000 works then let's set the accel to that, but if the default settings with accel disabled are better then let's disable the acceleration.  My true preference is for the user to have the best experience.

**Comment by eduncan911** [comment]
> My true preference is for the user to have the best experience.

Exactly!  I was already impressed with the updated Dremel PLA settings, changed from the default 220 to 210 or something, and initial first layer of 200.  :)

It's running now, but still seems jerky at 200/1000 with just 5.0 jerk.  Either that's just the way the mechnicals are, or the 3D20 stock firmware just ignores it.

200/1000 is what the stock firmware is (with 5.0 jerk).  So we could just check that in.

I do know the 3D45 settings above does give a much nicer experience - at the expense of about 5-10% slower overall print time.  You should try 800/1200 accel and 8.0 jerk on the 3D45 when you get home.  Actually, you can run a test print with both stock settings, and then insert these GCODE commands to adjust it.  Say, after 4 or 5 layers, insert these GCODE commands:

```
M201 X2000 Y2000 E2000 # sets the limits, which won't really be used
M204 P800 R800 T1200 # sets the effective acceleration
M205 X8.0 Y8.0 # set jerk on X and Y
```

Same goes for the 3D20, just different settings.  I'll try that on my next print to test what stock vs. adjusted settings does sound like right in the middle of a print.  Wouldn't be until tomorrow though...

But check the GCODE to see if Cura isn't already overriding these.  if you have accelleration and jerk enabled in Cura (I think they are under Speed), then Cura will constantly override these M204 and M205 commands quite often.  

Unchecking them will let the printer use it's firmware defaults, which you can then go into layer 5 or so and insert the commands above.

**Comment by timmehtimmeh** [comment]
@eduncan911 -  I've made the following changes & tested them - the actual print quality of Benchy with Dremel PLA (0.75kg) seems about the same on the 3D45 as before the changes, but as you mention the 3D45 is much less prone to vibration & making noise, and I'm confident that your suggested settings will improve the print quality in many situations.  Additionally, with the new settings the 3D20 Benchy is better.  

The table below summarizes the acceleration/jerk changes that I've made that will be available in plugin version 0.7.1.

|Setting | 3D20 | 3D40 | 3D45 |
|--------|-------|-------|-------|
| accel enabled | false | false | true |
| jerk enabled | false | false |true|
| acceleration_print* |  200 | 200| 800|
| acceleration_travel* | 1000 | 1000| 1200 |
| acceleration_travel_layer_0*  | 200 | 200| 1000|
| jerk_print^ |  5.0 | 5.0 | 8.0|
| jerk_travel^ |  5.0 | 5.0 | 8.0|
| jerk_travel_layer_0^ |  5.0 | 5.0 | 8.0|

\* = when the acceleration setting is enabled
^ = when the jerk setting is enabled

I've also given you credit in the [README](https://github.com/timmehtimmeh/Cura-Dremel-Printer-Plugin/tree/develop#contributors) for this plugin.  Please let me know if you want anything changed

I'll test a bit more over the next few days and then submit the updated plugin to Ultimaker for review

Thanks again for your help!
Cheers
Tim

**Comment by eduncan911** [comment]
Nice!  Yeah, the tests I ran were on some Print-in-Place alien-looking pliers my son wanted - and failed each time.  Nothing was free to rotate.  I decided to run an E-steps test, as I have never done it before, and realized it was greatly over-extruding!  So I've been dealing with that the last few days, to dial that in.  ([default E steps is 88.9 btw](https://github.com/moonglow/FlashForge_Marlin/blob/d26a00b08c14a414e6bb9801ad2706b1aeab6d5b/Marlin/Marlin/Configuration.h#L973))

Thank you for testing them!

IMO, I think we _should_ enable the settings by default.  Otherwise people may not know they are there?  Also, people would immediately see and hear the difference when using this plugin!

> I've also given you credit in the README for this plugin.

\**blush*\*

**Comment by timmehtimmeh** [comment]
@eduncan911 - FWIW I also ran [this part](https://www.thingiverse.com/thing:3160681) on the 3D45 using both the 0.7.0 plugin and the updated settings that I'll include in 0.7.1.  I forgot to turn off infill &  top & bottom layers so I ended up with a solid part, but both plugins seem to produce visually identical parts on the 3D45. (the ringing looks about the same & I don't see any layer shifts/skips.) 

I'm re-running the part on the 3D45 using the recommended settings for both version 0.7.0 and 0.7.1 of the plugin to see if it makes any difference (i doubt it will, but just to be safe) The reported print time between the two settings is 28minutes for the 0.7.0 plugin and 30 minutes for the 0.7.1 settings (~7 percent greater).  

Below are the settings that I'm running the new test at:

- 0.2 mm layer height
- 2 perimeters
- top/bottom layers: 0
- no infill

If the test goes well with the new settings then I'll give the two settings a try on the 3D20 with the `accel_enabled` and `jerk_enabled` settings set to true.  Assuming all of that goes well then I'll finalize the plugin & submit v0.7.1 to for Ultimaker for review.

>IMO, I think we should enable the settings by default. Otherwise people may not know they are there? Also, people would immediately see and hear the difference when using this plugin!

Ah - I think that I had misread your prior comment (below) and interpreted it to mean that you were recommending to turn off the setting.  
>the 3D20 is pretty loud on it's jerk settings, so I was going to set it to 5.0 from the Marlin firmware to see how it sounds on this next print in the next hour.

 I'll test with the settings enabled and assuming that it works as well/better then we'll leave them enabled.

**Comment by eduncan911** [comment]
> Ah - I think that I had misread your prior comment (below) and interpreted it to mean that you were recommending to turn off the setting.

Didn't misread at all!  Earlier I was recommending to set them to false, until we did more testing.  Well, you're doing that testing!!  hehe.  I didn't want to be the only one saying, "Hey, this worked for me" without far more testing.  So, let's enable them since they are working on a 2nd 3D45 and 3D20.  :)

**Comment by eduncan911** [comment]
For the record, I'm about to start hacking on our 3D20 in a week or two to install Klipper firmware on it, now that I have the pinouts from the Marlin repo.  That was a game changer!

**Comment by timmehtimmeh** [comment]
> I didn't want to be the only one saying, "Hey, this worked for me" without far more testing.

Fortunately it's easy to update software - if the settings end up not working, turning around a new plugin is relatively quick.

>let's enable them since they are working on a 2nd 3D45 and 3D20. :)

I'll make the changes once I finish testing the 3D20 tomorrow.  I'll probably leave the 3D40 accel and jerk disabled, as I don't have access to one, which makes tuning settings a guessing game at best.

**Comment by timmehtimmeh** [comment]
Release 0.7.1 with the requested changes is now available on the Cura Marketplace or in the [Releases page](https://github.com/timmehtimmeh/Cura-Dremel-Printer-Plugin/releases/tag/0.7.1) of this repo.

![image](https://user-images.githubusercontent.com/19733103/131202883-90cd2ae7-a544-4ab4-b812-181c97fc43be.png)


Cheers
Tim
